alert("Здравствуйте")
let Username = prompt("Как вас зовут")
console.log(Username)
let G = prompt("Ваш возраст")
console.log(G)
let I = prompt("Дата рождения")
console.log(I)
let R = prompt("Пол")
console.log(R)
let A = prompt("Место проживания")
console.log(A)
let S = prompt("Вид деятельности")
console.log(S)
let J = prompt("Почему вы выбираете эту работу")
console.log(J)
let U = prompt("Немного о себе")
console.log(U)
let J = prompt("Ваши навыки")
console.log(J)


